"""initial schema

Revision ID: 37d1b2631572
Revises: 
Create Date: 2026-10-03 22:46:24.961978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d1b2631572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('folder_ids', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embed_model', sa.String(length=200), nullable=True),
    sa.Column('embed_hash', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id')
    )
    with op.batch_alter_table('search_doc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_doc_table_id'), ['table_id'], unique=False)

    op.create_table('setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('delete_batch', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folder_delete_batch'), ['delete_batch'], unique=False)
        batch_op.create_index(batch_op.f('ix_folder_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_folder_parent_id'), ['parent_id'], unique=False)

    op.create_table('inv_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('delete_batch', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('content_updated_at', sa.DateTime(), nullable=False),
    sa.Column('content_updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_table_content_updated_at'), ['content_updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_table_delete_batch'), ['delete_batch'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_table_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_table_folder_id'), ['folder_id'], unique=False)

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('qty_type', sa.String(length=20), nullable=False),
    sa.Column('qty_value', sa.Float(), nullable=True),
    sa.Column('qty_unit', sa.String(length=30), nullable=False),
    sa.Column('qty_text', sa.String(length=200), nullable=False),
    sa.Column('qty_estimated', sa.Boolean(), nullable=False),
    sa.Column('custom', sa.JSON(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('delete_batch', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['inv_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_delete_batch'), ['delete_batch'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_table_id'), ['table_id'], unique=False)

    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_sha256'), ['sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_sha256'))
        batch_op.drop_index(batch_op.f('ix_photo_item_id'))

    op.drop_table('photo')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_table_id'))
        batch_op.drop_index(batch_op.f('ix_item_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_item_delete_batch'))

    op.drop_table('item')
    with op.batch_alter_table('inv_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_table_folder_id'))
        batch_op.drop_index(batch_op.f('ix_inv_table_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_inv_table_delete_batch'))
        batch_op.drop_index(batch_op.f('ix_inv_table_content_updated_at'))

    op.drop_table('inv_table')
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folder_parent_id'))
        batch_op.drop_index(batch_op.f('ix_folder_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_folder_delete_batch'))

    op.drop_table('folder')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_table('setting')
    with op.batch_alter_table('search_doc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_doc_table_id'))

    op.drop_table('search_doc')
    # ### end Alembic commands ###
